dolce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.url')),
    path('',include('accounts.url')),
    path('',include('blog.url')),
    path('',include('product.url')),
    path('',include('order.url')),
    path('',include('contact.url')),
    path('',include('shop.url')),
    url(r'^chaining/', include('smart_selects.urls')),

]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=150)
    message = models.TextField(max_length=1000)
    contacted_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

contact/views.py
from django.shortcuts import redirect, render
from contact.form import *
from utils import *


def ContactUs(request):
    context = {}

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        print('contact_form_error:', contact_form.errors)
        print('imm in post')
        if contact_form.is_valid():
            obj = contact_form.save()
            obj.save()
            print('Form Saved')
            sendEmailContact(obj,'',request) 
        else:
            return redirect('contact-us')

    contact_form = ContactForm(request.POST, prefix='contact_form')

    context['form'] = ContactForm()
    return render(request, 'contact_us.html', context=context)

contact/templates/contact_email.html
Below are the User that wants to cotact u:


{{obj.name}} <br>
{{obj.phone_number}} <br>
{{obj.email}} <br>
{{obj.subject}} <br>
{{obj.message}} <br>
{{obj.contacted_on}}<br>

contact/templates/contact_us.html
{% extends "base.html" %}

{% load static %}


{% block title %}
  Contact Us
{% endblock title %}

{% block css %}  
    <link rel="stylesheet" href="{% static 'assets/css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/media_query.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/contact_us.css' %}" />
{% endblock css %}

{% block content %}
      <!--------------******************------------ HEADER  END --------------******************---------->

    <!--------------******************---------- BreadCumb Start --------------******************---------->

    <div class="bread_cum">
        <div class="container-fluid">
            <div class="row bread_class">
                <div class="col-md-12">
                    <nav style="--bs-breadcrumb-divider: '>'" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="home.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Contact Us
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <!--------------******************---------- BreadCumb End --------------******************---------->

    <!-------------******************---------- Contact Us Section START-------------******************---------->
    <div class="container contact-us">
        <div class="row contact-title">
            <h3>
                Contact Us
            </h3>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce venenatis sit amet felis non sagittis.
                Vestibulum consectetur diam finibus magna tincidunt convallis. Lorem ipsum dolor sit amet, consectetur
                adipiscing elit.
            </p>
        </div>
    </div>

    <div class="container-fluid bg-white-2 ">
        <div class="row justify-content-evenly align-items-center">
            <div class="col-md-6 col-12">
                <div class="subscribe-form">
                    <div class="subscribe-form-top p-4 bg-white text-end">
                        <h4><strong class="form_title">GET IN TOUCH</strong></h4>
                        <p class="mb-0 form_text">
                            WE'D LOVE TO HEAR FROM YOU
                        </p>
                    </div>

                    <form id="p-form" method="POST" class="subscribe-form-bottom">
                         {% csrf_token %} 
                        <input type="text" name="name" placeholder="Name"
                            class="subscribe-input w-100 rounded form_input" required id="id_name">
                        <input type="text" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" id="phone_number"  name="phone_number" placeholder="Phone Number"
                        pattern=".{11,15}"
                        title="11 to 15 characters"
                        required
                        class="subscribe-input w-100 rounded form_input" required>
                        <div id="phone-error"></div>
                        <input type="email" name="email" placeholder="Email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
                            class="subscribe-input w-100 rounded form_input" required id="id_email">
                        <div id="email-error"></div>
                        <input type="text" name="subject" placeholder="Subject"
                            class="subscribe-input w-100 rounded form_input" required id="id_subject">
                        <textarea name="message" cols="40" rows="6" placeholder="Enter message here"
                            class="subscribe-input form-control w-100 rounded form_input" required=""
                            id="id_message"></textarea>

                        <input type="submit" value="SUBMIT" class="
                        bg-dark
                        text-white
                        w-100
                        rounded
                        form_subscribe_btn
                      ">
                    </form>
                </div>
            </div>
            <div class="col-md-6 col-12 p-0">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3614.1120324134636!2d55.13586171487269!3d25.064191683958207!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f6cb3268ae6ab%3A0xecce746348d028aa!2sHDS%20Business%20Centre%20-%20Cluster%20M%20-%20Jumeirah%20Lakes%20Towers%20-%20Dubai!5e0!3m2!1sen!2sae!4v1600085687693!5m2!1sen!2sae"
                    style="border: 0" allowfullscreen="" loading="lazy" class="mapframe mb-5 mb-md-0"></iframe>
            </div>
        </div>
    </div>

{% endblock content %}

{% block script %}
<script>
    const alertBox = document.getElementById("msg");
    const form = document.getElementById("p-form");
    const name = document.getElementById("id_name");
    const phone = document.getElementById("phone_number");
    const email = document.getElementById("id_email");
    const subject = document.getElementById("id_subject");
    const message = document.getElementById("id_message");
    const csrf = document.getElementsByName("csrfmiddlewaretoken");


    email.addEventListener('change', function validation() {
        var form = document.getElementById("p-form");
        var email = document.getElementById("id_email").value;
        var text = document.getElementById("email-error");
        var pattern = /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$/;

        if (email.match(pattern)) {
            form.classList.remove("invalid");
            document.getElementById("email-error").style.display = "none";
        } else {
            document.getElementById("email-error").style.display = "block";
            form.classList.add("invalid");
            text.innerHTML = '<p class="error">Invalid Email</p>';
        }
    });

    // phone.addEventListener('change', function validation() {
    //     var form = document.getElementById("p-form");
    //     var phone = document.getElementById("phone_number").value;
    //     var p_text = document.getElementById("phone-error");
    //     // // var p_pattern = /[+]{1}[0-9]{11}/;
    //     // var p_pattern = /[0-9]{11}/;

    //     // if (phone.match(p_pattern)) {
    //     //     form.classList.remove("p-invalid");
    //     //     document.getElementById("phone-error").style.display = "none";
    //     // } else {
    //     //     document.getElementById("phone-error").style.display = "block";
    //     //     form.classList.add("p-invalid");
    //     //     p_text.innerHTML = '<p class="p_error">Invalid Phone Number</p>';
    //     // }
    // });

    form.addEventListener("submit", function (e) {
        e.preventDefault();

        const fd = new FormData();
        fd.append("csrfmiddlewaretoken", csrf[0].value);
        fd.append("name", name.value);
        fd.append("phone_number", phone.value);
        fd.append("email", email.value);
        fd.append("subject", subject.value);
        fd.append("message", message.value);

        $.ajax({
            type: "POST",
            // url: "",
            enctype: "multipart/form-data",
            data: fd,
            success: function (response) {
                console.log(response);
                name.value = "";
                phone.value = "";
                email.value = "";
                subject.value = "";
                message.value = "";

                // Universal ALert Box Script START
                $('.alert').addClass("show");
                $('.alert').removeClass("hide");
                $('.alert').addClass("showAlert");
                setTimeout(function () {
                    $('.alert').removeClass("show");
                    $('.alert').addClass("hide");
                }, 7000);
                alertBox.innerHTML = `Successfully Submitted`;
                // Universal ALert Box Script END
            },
            error: function (error) {
                // Universal ALert Box Script START
                $('.alert').addClass("show");
                $('.alert').removeClass("hide");
                $('.alert').addClass("showAlert");
                setTimeout(function () {
                    $('.alert').removeClass("show");
                    $('.alert').addClass("hide");
                }, 7000);
                alertBox.innerHTML = `Invalid Details`;
                // Universal ALert Box Script END
            },
            cache: false,
            contentType: false,
            processData: false,
        });
    });
</script>
{% endblock script %}